name: RefluxSurvivalScoreboard Build

on:
  push:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip]')"
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17
        server-id: github
        cache: 'maven'
        
    - name: Cache maven repo
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
      
    - name: Build
      run: mvn package --file pom.xml
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: RefluxSurvivalScoreboard
        path: target/RefluxSurvivalScoreboard-1.0.0.jar 
